### PR TITLE
feat: telemetry modal

### PR DESCRIPTION
**Pull request by andreiv1992**
## Changes

- adds a notification for users who have not interfered with telemetry data

## Fixes

- fix: #1512 

## How to test it

- if you've played with the telemetry data just add these somewhere in the code the on the next reload the telemetry modal should show
`
electronStore.delete('appConfig.disableEventTracking');
electronStore.delete('appConfig.disableErrorReporting');
`

## Screenshots

- https://user-images.githubusercontent.com/5509112/161067277-58fad75a-d29d-45a4-bfef-c84201efb1c2.mov

## Checklist

- [x] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

### CODE REVIEW

**Comment by devcatalin** [comment]
image
I think these two buttons should disappear after you click on either one of them. What do you think @julioramosest ?

**Comment by andreiv1992** [comment]
> image
> 
> I think these two buttons should disappear after you click on either one of them. What do you think @julioramosest ?

I can delete the notification if the user clicks on either one of those buttons, this is much easier

**Comment by andreiv1992** [comment]
> @andreiv1992 @devcatalin you can choose from one of these options
> 
> * After click on any option, the buttons are substituted with a plain text that says "Your settings have been saved."
> * The whole alert is substituted by a text that says "your telemetry settings have been saved."
> 
> deleting the whole thing can feel too sudden.

Let me know if this is ok
https://user-images.githubusercontent.com/5509112/161590803-4b3476ed-9a20-476c-b8e4-529dce691810.mov

**Comment by julioramosest** [comment]
@andreiv1992 Fine for me, per the video. Thanks!

**Review by devcatalin — APPROVED** [review]
LGTM

**Pull request merged**
