### PR TITLE
fix(docs): update to include .rpm binaries

### PR DESCRIPTION
**Pull request by dipankardas011**
This PR...

## Changes

- changes to documentation according to #2654

## Fixes

- updates to monokle documentation page

## How to test it
- 

## Screenshots

-

## Checklist

- [ ] tested locally
- [ ] added new dependencies
- [x] updated the docs
- [ ] added a test

### CODE REVIEW

**Review by olensmar — APPROVED** [review]

**Review by topliceanurazvan — CHANGES_REQUESTED** [review]

**Comment by dipankardas011** [comment]
@topliceanurazvan made the changes

**Review by topliceanurazvan — DISMISSED** [review]

**Comment by topliceanurazvan** [comment]
Hey @dipankardas011, can you fix conflicts for this so we can merge it?

**Comment by topliceanurazvan** [comment]
Try to merge main into your branch, you should be able to fix it from there

**Comment by dipankardas011** [comment]
> Try to merge main into your branch, you should be able to fix it from there

Sure

**Comment by dipankardas011** [comment]
Done

**Review by topliceanurazvan — APPROVED** [review]

**Pull request merged**
