### PR TITLE
fix: quick search tooltip & resize settings icons

### PR DESCRIPTION
**Pull request by mortada-codes**
This PR...

## Changes

- added a tooltip for quick search 
- set setting icons size 18px

## Fixes

-

## How to test it

-

## Screenshots

- 
Screen Shot 2022-01-26 at 1 59 51 PM

## Checklist

- [x] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

### CODE REVIEW

**Review by DmitryEremenko — APPROVED** [review]
LGTM

**Review by erdkse — COMMENTED** [review]
Notifications icon actually is 14x14 - the other are good

**Comment by erdkse** [comment]
Tooltip message would be `Filter results – Hint: quick-filter using CTRL + P`

**Review by erdkse — APPROVED** [review]
LGTM!

**Pull request merged**
