### PR TITLE
refactor: save duplicate resources with suffix

### PR DESCRIPTION
**Pull request by topliceanurazvan**
## Changes

- No longer replace duplicate resources, but save to files with suffixes.

## Screenshots

image

## Checklist

- [x] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

### CODE REVIEW

**Comment by olensmar** [comment]
wondering if we could suggest different filenames based on some other algorithm - for example add the resource-kind - before resorting to numbers!? i.e. if Monokle detects multiple objects with the same name it automatically attempts to generate filenames  with  name-kind.yaml !?

**Comment by topliceanurazvan** [comment]
@olensmar - great suggestion. We can definitely try to do that.

**Comment by topliceanurazvan** [comment]
@olensmar - We are now generating filenames including the kind. PR is ready to be reviewed.

**Review by olensmar — APPROVED** [review]
nice!

**Pull request merged**
