### PR TITLE
refactor: actions pane footer

### PR DESCRIPTION
**Pull request by topliceanurazvan**
## Changes

- Redesign of the actions pane footer
- Make actions pane footer resizable 

## Screenshots

image

image

## Checklist

- [x] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

### CODE REVIEW

**Comment by olensmar** [comment]
Looks good - although I thought the Terminal was going to span the entire window!? (maybe this is just an example)

**Comment by topliceanurazvan** [comment]
@olensmar - the terminal it's just an example, this was made after the design from https://github.com/kubeshop/monokle/issues/731 , we can show there any content like `Documentation`, `Terminal` etc.. 

Maybe we can have multiple tabs in this footer that could be useful for the user. @devcatalin @tommywhitehead wdyt?

**Comment by olensmar** [comment]
> @olensmar - the terminal it's just an example, this was made after the design from #731 , we can show there any content like `Documentation`, `Terminal` etc..
> 
> Maybe we can have multiple tabs in this footer that could be useful for the user. @devcatalin @tommywhitehead wdyt?

thanks - that's what I thought! Definitely agree on multiple tabs!

**Comment by erdkse** [comment]
I prefer the multiple tabs to be on an entire pane - not separated panes for each

**Review by devcatalin — APPROVED** [review]
This works nicely, good job!

**Pull request merged**
