### PR TITLE
feat: add cluster context status to header

### PR DESCRIPTION
**Pull request by erdkse**
This PR...

## Changes

- Add cluster status to header

## Fixes

-

## How to test it

-

## Screenshots

-

## Checklist

- [ ] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

### CODE REVIEW

**Comment by olensmar** [comment]
nice work @erdkse !- with long cluster names the wrapping isn't optimal - can it be made wider?
image

**Comment by erdkse** [comment]
Done @olensmar

**Comment by olensmar** [comment]
thanks @erdkse - also we should disable the dropdown when in cluster-preview mode - as we do in the cluster-pane to the left.

**Comment by erdkse** [comment]
Sorry @olensmar missed that! Done again

**Review by olensmar — APPROVED** [review]
thank you!

**Pull request merged**
