### PR TITLE
Fixed clicking outside resource label not selecting the item

### PR DESCRIPTION
**Pull request by KarthikRaju391**
This PR...

## Fixes

- Clicking on the resource label not selecting the item

## How to test it

- Click anywhere on the resource label

## Checklist

- [x] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

### CODE REVIEW

**Review by topliceanurazvan — CHANGES_REQUESTED** [review]
Looks good, the only think that we still need to do is not highlight the element when clicking on the three dots for showing the menu ( this should happen for all section blueprints that contains `ContextMenu`

**Comment by KarthikRaju391** [comment]
@topliceanurazvan, so, when we click on the three dots, the item shouldn't be highlighted right?

**Comment by topliceanurazvan** [comment]
> @topliceanurazvan, so, when we click on the three dots, the item shouldn't be highlighted right?

Yes

**Comment by KarthikRaju391** [comment]
> @topliceanurazvan, so, when we click on the three dots, the item shouldn't be highlighted right?

@topliceanurazvan, I am not able to find a way to make it that way

**Comment by topliceanurazvan** [comment]
> > @topliceanurazvan, so, when we click on the three dots, the item shouldn't be highlighted right?
> 
> @topliceanurazvan, I am not able to find a way to make it that way

Hey @KarthikRaju391 , a solution would be to stop the event propagation on the click of the three dots

**Comment by KarthikRaju391** [comment]
@topliceanurazvan, I think I have fixed the even propogation problem

**Review by topliceanurazvan — APPROVED** [review]
Looks good to me! Great work 🙌🏻

**Pull request merged**
