### PR TITLE
refactor: new resource creation

### PR DESCRIPTION
**Pull request by topliceanurazvan**
## Changes

- Replace the collapse/expand icon for both the navigator and file tree
- Remove new folder from file tree header
- Change plus button for creating a new resource with label `New`
- Change new resource dropdown items label
- Add new resource cards when the navigator is empty
- Remove `highlightedItems`

## Screenshots

image

image

## Checklist

- [x] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

### CODE REVIEW

**Comment by topliceanurazvan** [comment]
@julioramosest @olensmar @devcatalin Let me know if we need to change the labels from the new resource dropdown items

**Comment by julioramosest** [comment]
- Not sure about the radius and the font weight of the new CTA. Radius needs to be 3px, font is semibold, 12px
- the expand icon in the resources column. Needs to be link-blue by default

as for the labels: Thomas suggested "New from model" to be "Create manually" or sort of...

**Comment by olensmar** [comment]
@DzoQiEuoi @CortNick  do you have some suggestions on how to improve these labels? I was thinking something in line of

New
- From scratch / schema
- From advanced template
- Using GPT query

**Comment by devcatalin** [comment]
I like the options mentioned by Ole, although I would go for "Using AI prompt" as the third one.

The "New from model" option is the most confusing one at the moment, at least for me.
I like the "New from scratch" better, or we could say "Using general form" 🤔

**Comment by DzoQiEuoi** [comment]
I was thinking:

- Create manually
- Use a template
- Generate via AI

**Comment by olensmar** [comment]
ok since everyone has different suggestions i'll make the call:
- Create manually
- Use Advanced Template
- AI Assisted

**Review by mortada-codes — APPROVED** [review]

**Pull request merged**
