### PR TITLE
feat : filter resource by file/folder

### PR DESCRIPTION
**Pull request by topliceanurazvan**
This PR implements the functionality to filter resources by file/folder.

## Changes

- Add new filter `Contained in` in resource filters which filters resources by file/folder
- Add option to apply filtering on file/folder in `FileTreePane ContextMenu`

## Checklist

- [x] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

### CODE REVIEW

**Comment by olensmar** [comment]
looks great @topliceanurazvan - only suggestion is to change the header to "Contained in file/folder" and move this section to the bottom of the filter panel

**Comment by olensmar** [comment]
thanks @topliceanurazvan - it works very nicely - could we perhaps "grey out" files in the file explorer that are not included in the current filter!?

**Comment by topliceanurazvan** [comment]
Nice suggestion @olensmar , I will do the changes.

**Comment by olensmar** [comment]
thanks @topliceanurazvan - one last request - change the "File on this file/folder" action for the file/folder currently being filtering on to "Remove from filter" - which would remove the file/folder from the filter. In this way it is easy to first filter on a file/folder - and then remove that filter again... (hope that makes sense)

**Comment by topliceanurazvan** [comment]
@olensmar - Got it, I've made the change.

**Review by olensmar — APPROVED** [review]
awesome!

**Pull request merged**
