### PR TITLE
Erdikose/fix/create secret form from scratch

### PR DESCRIPTION
**Pull request by erdkse**
This PR...

## Changes

- add SecretForm

## Fixes

-

## How to test it

-

## Screenshots

-

## Checklist

- [ ] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

### CODE REVIEW

**Review by olensmar — COMMENTED** [review]
Looks great @erdkse! - did you consider bypassing the  react-json-schema-form-component all-together and create a custom SecretForm react component?

**Comment by erdkse** [comment]
> Title

I did it on purpose - so the data is handled by RJSF. It makes our work easier in my opinion.

**Comment by olensmar** [comment]
> > Title
> 
> I did it on purpose - so the data is handled by RJSF. It makes our work easier in my opinion.

good point - thanks for clarifying!

**Review by olensmar — APPROVED** [review]
very nice!

**Pull request merged**
