### PR TITLE
feat: improved syntax error messages and position, added links to popup

### PR DESCRIPTION
**Pull request by olensmar**
## Checklist

- [X] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [X] added a test

image

### CODE REVIEW

**Comment by olensmar** [comment]
I think this also removes the need for #332 for now since the validation messages we get from ajv are the same as shown in the editor - i'm guessing they use ajv under the hood also

**Comment by olensmar** [comment]
@tommywhitehead please let me know if you have any comments on the formatting in the popup

**Comment by olensmar** [comment]
> Should we use dots instead of slashes for the object paths?

the path comes from the ajv validator as a JsonPointer - we can replace the slashes with dots if that makes it easier to read!?

**Review by devcatalin — APPROVED** [review]
LGTM

**Comment by devcatalin** [comment]
> the path comes from the ajv validator as a JsonPointer - we can replace the slashes with dots if that makes it easier to read!?

Maybe another question for Thomas?

**Pull request merged**
