### PR TITLE
fix: file typo

### PR DESCRIPTION
**Pull request by topliceanurazvan**
## Fixes

- Rename `Styled.tsx` to `styled.tsx`

## Checklist

- [ ] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

### CODE REVIEW

**Comment by erdkse** [comment]
Already merged

**Comment by topliceanurazvan** [comment]
@erdkse - yes, I just renamed it to lowercase so we are having it consistent in all files. Not necessary maybe though? 🤔

**Comment by erdkse** [comment]
> @erdkse - yes, I just renamed it to lowercase so we are having it consistent in all files. Not necessary maybe though? 🤔

ahh ok then - I thought you solved the same issue

**Review by erdkse — APPROVED** [review]
lgtm

**Pull request merged**
