### PR TITLE
feat: option to show cluster only resources in cluster compare

### PR DESCRIPTION
**Pull request by devcatalin**
This PR...

## Changes

- added "Show all" option under "Cluster resources" title
- improved Cluster Compare styling

## Fixes

-

## How to test it

-

## Screenshots

image

image

## Checklist

- [x] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

### CODE REVIEW

**Review by topliceanurazvan — CHANGES_REQUESTED** [review]
Nice styling refactor! 👍🏻 

I found a problem though, somehow the width of the modal can get lower than the one of the grid container, and it hides the scrollbar and some content from the right column ( see the attached screenshot ).

image

**Comment by olensmar** [comment]
thanks @devcatalin - looks good! 

I found a couple of issues - not sure they are related - see screenshot below:
- when selecting resources that exist only in the cluster and not locally Monokle enables the "deploy selected resources to cluster" option - I think it should enable the other button instead!?
- the count displayed in the enabled button is for all resources - not the just the filtered/selected ones

image

**Comment by devcatalin** [comment]
I pushed two commits fixing the following:
- styling/responsiveness issue
- clearing selected matches when filters are changed
- disabled/enabled state of the deploy and replace buttons

@olensmar , I have the following questions:
1. Should we disable changing filters when a selection is made or is it okay to clear selections?
2. The replace is currently enabled only when both local resource and cluster resource exist. 
To enable it when only the cluster resource exist, we have to decide how we would save the resources.
Should I just create unsaved resources? 
Or do we add an inputs to select a folder or a file where the resources should be saved? - in this case maybe the word "Replace" is not that great

**Comment by devcatalin** [comment]
For the second question related to "replace" action, I could do it in a separate PR when I implement this: https://github.com/kubeshop/monokle/issues/841

**Comment by devcatalin** [comment]
@olensmar @topliceanurazvan this is ready for review & merge

**Review by topliceanurazvan — CHANGES_REQUESTED** [review]
Great work! 👍🏻 The only problem that I encountered is that with some filters applied ( the namespace in my case), after clicking on the `Select all` checkbox, that number of selected resources is much bigger than the actual selected resources ( see the attached screenshot).

image

**Comment by devcatalin** [comment]
fixed the "select all" checkbox

**Review by topliceanurazvan — APPROVED** [review]

**Pull request merged**
