### PR TITLE
build: splitter style enhancement done as requested

### PR DESCRIPTION
**Pull request by sriniva7**
This PR...

## Changes

- #2012 

## How to test it

- Check the draggable between the pane

## Checklist

- [x] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

### CODE REVIEW

**Review by szmski — APPROVED** [review]

**Comment by sriniva7** [comment]
> Visual for the splitters is correct, 1px wide. Looks fine. Although click and drag action is UX sufficient, it would be interesting that we could investigate for the active area (the area in which the cursor is active for clicking and dragging) to be a bit wider (4pxls or so) so clicking happens more easily.

Sure @julioramosest I do try and give update on that

**Comment by julioramosest** [comment]
thank you @sriniva7 for your kind effort!

**Comment by julioramosest** [comment]
Hi there @sriniva7 were you able to investigate a bit around the active area for the clicking and dragging of the separators?

**Comment by sriniva7** [comment]
> Hi there @sriniva7 were you able to investigate a bit around the active area for the clicking and dragging of the separators? 

I did, but I cannot do any progress.

**Comment by julioramosest** [comment]
I would go with merging what we have then: the 1px dividers and that's it. Thanks for your time on this @sriniva7!

**Comment by sriniva7** [comment]
>  I would go with merging what we have then: the 1px dividers and that's it. Thanks for your time on this @sriniva7!

Thanks

**Review by topliceanurazvan — APPROVED** [review]
Great work @sriniva7 🙌🏻

**Pull request merged**
