### PR TITLE
feat(rpm): Addition of rpm release 

### PR DESCRIPTION
**Pull request by dipankardas011**
Signed-off-by: Dipankar Das <dipankardas0115@gmail.com>

This PR...

## Changes

- Addition of ~Flatpak~ rpm
reason:
after `deb` the most number of users are from `rpm` 

## Fixes

- Issue #844 

## Checklist

- [x] tested locally
- [x] added new dependencies
- [ ] updated the docs
- [ ] added a test

### CODE REVIEW

**Comment by erdkse** [comment]
hey @dipankardas011 , this will need a separate build operation for flatpak. Why not build the application with electron-builder?

**Comment by dipankardas011** [comment]
Will improve✌️

**Comment by chargio** [comment]
Great to see this!

**Comment by dipankardas011** [comment]
Addition of support for `rpm` build rather than `flatpak`

**Comment by dipankardas011** [comment]
@erdkse @chargio could you check if it still hold good?

**Comment by chargio** [comment]
Thanks.

We found some problems before but we need this done
@erdkse Can you look at it?

**Review by erdkse — APPROVED** [review]

**Review by erdkse — APPROVED** [review]

**Pull request merged**
