### PR TITLE
chore(release): 2.4.5

### PR DESCRIPTION
**Pull request by monojack**
This PR...

## Changes

-

## Fixes

-

## How to test it

-

## Screenshots

-

## Checklist

- [x] tested locally
- [x] added new dependencies
- [ ] updated the docs
- [ ] added a test

### CODE REVIEW

**Comment by olensmar** [comment]
@monojack could we check if there are any major electron/electron-builder upgrades available?

**Comment by monojack** [comment]
> @monojack could we check if there are any major electron/electron-builder upgrades available?

Electron has 2 major increments. I took a quick look at the documented breaking changes and tried a search through the source code - looks like we're not using any of the changed/deprecated/removed symbols. 

image

**Comment by olensmar** [comment]
thanks @monojack - perhaps there is a 27.X upgrade that we should use for security fixes that won't break our build?

**Comment by monojack** [comment]
Was just checking 27.x and 28.x, they both work. Which one would you like??

**Comment by olensmar** [comment]
then I'd go for 28 - thanks!

**Review by olensmar — APPROVED** [review]

**Pull request merged**
