### PR TITLE
feat: displayed the Warning icon if the user did not specify the path to kubeconfig

### PR DESCRIPTION
**Pull request by Toxer10**
This PR...

## Changes

- WIP: displayed the Warning icon if the user did not specify the path to kubeconfig

### CODE REVIEW

**Review by catalinhoha — APPROVED** [review]

**Comment by olensmar** [comment]
the blue exclamation mark doesn't seem to go away once i've entered a valid context
image

**Review by olensmar — CHANGES_REQUESTED** [review]
please fix the exclamation mark as noted in the comment

**Comment by Toxer10** [comment]
> please fix the exclamation mark as noted in the comment - I also noticed that it shows when starting Monokle with a previous kubeconfig (valid) set... is this intentional?

No, as I said I did not cover some edge cases

**Comment by Toxer10** [comment]
> please fix the exclamation mark as noted in the comment - I also noticed that it shows when starting Monokle with a previous kubeconfig (valid) set... is this intentional?

This was fixed in the last commit. Clear your electron cache before checking

**Comment by catalinhoha** [comment]
Don't forget to change the blue exclamation icon to a simple blue dot, keep the yellow&red ones as they are

**Review by olensmar — APPROVED** [review]

**Pull request merged**
