### PR TITLE
feat: added preview menu item to kustomization and helm-vaues files 

### PR DESCRIPTION
**Pull request by olensmar**
This PR...

## Changes

-

## Fixes

-

## How to test it

-

## Screenshots

-

## Checklist

- [X] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

image

### CODE REVIEW

**Review by topliceanurazvan — COMMENTED** [review]
Nice UX improvement 👍🏻 Maybe we should add the `Preview` action to the ContextMenu of `Kustomization Pane` and `Helm Pane`  to be consistent?
image

**Comment by olensmar** [comment]
not sure it's needed there since we have a dedicated Preview action next to the menu!? @tommywhitehead what do you think?

**Comment by olensmar** [comment]
@topliceanurazvan good catch on the context menu - i'll fix that in this PR..

**Review by topliceanurazvan — APPROVED** [review]
lgtm!

**Review by devcatalin — APPROVED** [review]

**Pull request merged**
