### PR TITLE
fix: hide left menu icons badges after pane opens

### PR DESCRIPTION
**Pull request by devcatalin**
This PR...

## Changes

- the blue dot/badge should be hidden after we click on the kustomization / helm charts icons
- it should appear again when changing the folder, if there are any kustomizations or helm charts in that folder

## Fixes

-

## How to test it

-

## Screenshots

-

## Checklist

- [ ] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

### CODE REVIEW

**Review by erdkse — APPROVED** [review]
LGTM!

**Comment by olensmar** [comment]
actually I don't agree with this - why would we hide it? I think it's helpful to have it there even after I've opened those panes (i'm forgetful..)

**Comment by devcatalin** [comment]
> actually I don't agree with this - why would we hide it? I think it's helpful to have it there even after I've opened those panes (i'm forgetful..)

I was thinking it's just a hint that there are kustomizations in the pane, I'm expecting to see something "new" when I see that badge. If I remember correctly, this is how @tommywhitehead said we should do it..

**Comment by olensmar** [comment]
ok let's merge and discuss with @tommywhitehead

**Pull request merged**
