### PR TITLE
feat: auto import sorting

### PR DESCRIPTION
**Pull request by Toxer10**
This PR...

## Changes

- Added auto import sorting. To discuss with the team

### CODE REVIEW

**Comment by erdkse** [comment]
Do we have to install an extension for this?

**Comment by Toxer10** [comment]
Yes. I found one for VS Code called TypeScript Import Sorter https://marketplace.visualstudio.com/items?itemName=mike-co.import-sorter. Do we need the one which works not only in VS Code?

**Comment by olensmar** [comment]
@Toxer10 we need one that works with es-lint or something similar - it should be automated as a pre-commit hook and  shouldn't require any specific editor

**Review by olensmar — APPROVED** [review]
LGTM

**Pull request merged**
