### PR TITLE
fix: section quick create button color

### PR DESCRIPTION
**Pull request by devcatalin**
This PR...

## Changes

-

## Fixes

From:
image

To:
image

## How to test it

-

## Screenshots

-

## Checklist

- [ ] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

### CODE REVIEW

**Review by olensmar — APPROVED** [review]
LGTM - but to be honest I often mistakenly click on this button when I want to expand a section - perhaps it was a bad idea (of mine..) to put it here in the first place!?

**Comment by devcatalin** [comment]
it also might be confusing to have two Plus buttons like in the screenshots above?
we could remove it entirely..

**Comment by olensmar** [comment]
> it also might be confusing to have two Plus buttons like in the screenshots above? we could remove it entirely..

exactly @tommywhitehead what do you suggest? can we make it different so we don't have two plus-buttons? or should we remove?

**Comment by olensmar** [comment]
I think we can merge this and discuss on the UX call if we should keep it!?

**Pull request merged**
