### PR TITLE
feat: added expand/collapse buttons in file explorer tree

### PR DESCRIPTION
**Pull request by Toxer10**
## Changes

- Added expand/collapse buttons

### CODE REVIEW

**Comment by olensmar** [comment]
looks like the icon is getting on the wrong side of the divider when cramped - can we fix this?

**Comment by Toxer10** [comment]
image
It happens in the middle too. We should change the layout to prevent this behavior on all sides: left, middle, and right.

**Comment by olensmar** [comment]
Yes - please look into this!

**Review by olensmar — APPROVED** [review]
lgtm!

**Pull request merged**
