### PR TITLE
feat: Cluster Compare modal resizable

### PR DESCRIPTION
**Pull request by topliceanurazvan**
## Changes

- Resizable Cluster Compare Modal
- Resizable Resource Diff Modal

## Checklist

- [x] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

### CODE REVIEW

**Comment by devcatalin** [comment]
Need to fix two things:
- the Skeleton is out of the modal body when Cluster Compare initially loads
- ItemRenderer styling because the Suffix icons were moved to far right in the Navigator

**Comment by olensmar** [comment]
thanks @topliceanurazvan - looking good! It seems this doesn't apply to the standalone Diff - will that be in this PR also or in a separate one?

**Comment by topliceanurazvan** [comment]
> thanks @topliceanurazvan - looking good! It seems this doesn't apply to the standalone Diff - will that be in this PR also or in a separate one?

@olensmar We will add it in this PR.

**Review by devcatalin — APPROVED** [review]
Nice work!

**Pull request merged**
